import type { Metadata } from "next";
import { SITE_ORIGIN } from "@/lib/siteOrigin";
import localFont from "next/font/local";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { ExitPreviewButton } from "@/components/ExitPreviewButton";
import "./globals.css";

// Self-hosted (not next/font/google) so the build never depends on Google's
// font CDN being reachable — both files are variable fonts covering the
// weight range we use, downloaded once into public/fonts.
const baloo2 = localFont({
  src: "../public/fonts/Baloo2-Variable.woff2",
  variable: "--font-baloo-2",
  weight: "600 800",
  display: "swap",
});

const instrumentSans = localFont({
  src: "../public/fonts/InstrumentSans-Variable.woff2",
  variable: "--font-instrument-sans",
  weight: "400 700",
  display: "swap",
});

const SITE_NAME = "Forest Circuit";
/**
 * The circuit mark in white on brand green, drawn at 1200x630 — the size every
 * platform crops its preview from. Generated by scripts/build-share-image.ts;
 * regenerate it there rather than editing the PNG by hand.
 */
const SHARE_IMAGE = "/images/og-share.png";
const SITE_DESCRIPTION =
  "Forest Methodist Circuit is a team ministry of ten churches across East London and Essex. Find a church, worship with us, and get involved in your community.";

/**
 * Link-preview scrapers (WhatsApp, iMessage, Slack...) fetch og:image as a
 * standalone request — a relative path only works if it happens to resolve
 * against whichever domain the scraper reaches. Before forestcircuit.co.uk
 * is cut over to this app, that domain still serves the old site and 404s
 * on this path, so the image needs to be resolved against whatever host is
 * actually serving this build.
 *
 * Vercel sets VERCEL_PROJECT_PRODUCTION_URL at build time to the project's
 * current production domain — right now that's the vercel.app alias, and it
 * becomes forestcircuit.co.uk automatically the day that domain is attached
 * as Production, with no code change needed. Read at build time (not from
 * request headers) so pages stay statically generated rather than forced
 * dynamic on every request.
 */
const SHARE_IMAGE_URL = `${SITE_ORIGIN}${SHARE_IMAGE}`;

export const metadata: Metadata = {
  metadataBase: new URL("https://www.forestcircuit.co.uk"),
  title: {
    default: "Forest Circuit | Methodist churches across Waltham Forest, Wanstead and Loughton",
    template: "%s | Forest Circuit",
  },
  description: SITE_DESCRIPTION,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: "Forest Circuit | Methodist churches across Waltham Forest, Wanstead and Loughton",
    description: SITE_DESCRIPTION,
    url: "/",
    images: [{ url: SHARE_IMAGE_URL, width: 1200, height: 630, alt: "Forest Methodist Circuit" }],
    locale: "en_GB",
  },
  twitter: {
    card: "summary_large_image",
    title: "Forest Circuit | Methodist churches across Waltham Forest, Wanstead and Loughton",
    description: SITE_DESCRIPTION,
    images: [SHARE_IMAGE_URL],
  },
};

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Forest Methodist Circuit",
  url: "https://www.forestcircuit.co.uk",
  logo: "https://www.forestcircuit.co.uk/images/logo-ink.png",
  description: SITE_DESCRIPTION,
  areaServed: "Waltham Forest, Wanstead and Loughton",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled: preview } = await draftMode();

  return (
    <html lang="en" className={`${baloo2.variable} ${instrumentSans.variable}`}>
      <body className="antialiased">
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }} />
        {children}
        {preview && (
          <>
            <VisualEditing />
            <ExitPreviewButton />
          </>
        )}
      </body>
    </html>
  );
}
